version: "3.9"

services:
  subscribers-db:
    image: mysql:8.0
    container_name: subscribers
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WP_DATABASE_NAME}
      MYSQL_USER: ${WP_DATABASE_USER}
      MYSQL_PASSWORD: ${WP_DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - /tmp/landing/mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
  frontend:
    image: wordpress:5.1.1-fpm-alpine
    container_name: frontend
    restart: always
    environment:
      WORDPRESS_DB_NAME: ${WP_DATABASE_NAME}
      WORDPRESS_DB_HOST: ${WP_DATABASE_HOST}
      WORDPRESS_DB_USER: ${WP_DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DATABASE_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - subscribers-db
  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
volumes:
  wordpress:

